### ISSUE TITLE
Peptide sequence is shown without modifications in the hover tool

### ISSUE THREAD

**Issue by EugeniaVoytik** [MannLabs/alphamap#15]
### Issue: 
In case when the same peptide was identified in several runs and modified only in one case (e.g. oxidated), then in the hover tool for the peptide sequence we see a one without modifications but the PTM information is still there.

Look at the attached screenshot: 
![issue_alphamap](https://user-images.githubusercontent.com/33324675/126766547-81ffdbbd-3dff-467d-836a-b8076906c30b.png)

**Comment by ibludau** [comment]
The hover info now shows info for all peptides covering a given amino acid.
<img width="894" alt="Screenshot 2021-07-27 at 16 57 30" src="https://user-images.githubusercontent.com/20396322/127177259-5acd8981-b627-4cda-b52c-492210024646.png">
