### ISSUE TITLE
To add a specific marker shape for still not included modifications in the AlphaMap

### ISSUE THREAD

**Issue by EugeniaVoytik** [MannLabs/alphamap#16]
### Feature:

If the modification is not present in the list of known modifications in AlphaMap, add an assigned form of the marker for it that is shown on the plot.

**Comment by ibludau** [comment]
This was already implemented and should work :-)
![newplot (78)](https://user-images.githubusercontent.com/20396322/127338621-043608b6-4350-4053-b254-3fb9a8f756b2.png)
