### ISSUE TITLE
Some modifications are not shown on the plot

### ISSUE THREAD

**Issue by EugeniaVoytik** [MannLabs/alphamap#17]
### Issue:

In some cases, modifications that are present in the data are not included in the legend of the plot and not shown. See attached example:
![issue_alphamap2](https://user-images.githubusercontent.com/33324675/126767896-eb36c287-f014-4eeb-a042-757eba10bde0.png)

**Comment by ibludau** [comment]
There was a bug for n-terminal modifications which I fixed in the preprocessing functions.
<img width="911" alt="Screenshot 2021-07-27 at 16 59 10" src="https://user-images.githubusercontent.com/20396322/127177569-26c219c3-1fcd-459d-933c-ce29e7ad46a5.png">
