### ISSUE TITLE
MSFragger / FragPipe integration

### ISSUE THREAD

**Issue by hcadre** [MannLabs/alphamap#23]
It would be very helpful to also have the possibility to upload results from a search performed with FragPipe (combined_peptide.tsv?). 
Thank you for this tool!

**Comment by ibludau** [comment]
Thanks for the suggestion to include FragPipe output. 
We're still expanding on the input formats and can certainly aim to incorporate that for the next release!

**Comment by hcadre** [comment]
Purrfect! Thanks!

**Comment by EugeniaVoytik** [comment]
Thank you for suggesting this feature! We've integrated two options that Isabell mentioned in the previous comment. You may read more about it in the instructions for the import of FragPipe output files in AlphaMap in GUI directly or in the README.md file.
