### ISSUE TITLE
Launching server at http://localhost:53026 WARNING:tornado.access:404 GET /favicon.ico (::1) 1.00ms

### ISSUE THREAD

**Issue by miaohaofei** [MannLabs/alphamap#26]
hi!
   when i installed the alphamap on windows as your mannual, In the last step, it came  out like this"Launching server at http://localhost:53026
WARNING:tornado.access:404 GET /favicon.ico (::1) 1.00ms",and it did not work .  what is the problem? Any suggestion for solving this problem?  Thank you very much!

**Comment by ibludau** [comment]
Hey, thanks a lot for your message. The warning "WARNING:tornado.access:404 GET /favicon.ico" is normal and usually shows up, so this should not be the issue. 
Did you check your browser window if alphamap actually started? 
If not, could you please let me know your operating system and version?
Cheers,
Isabell
