### ISSUE TITLE
Do I need to use Uniprot? 

### ISSUE THREAD

**Issue by rugenni** [MannLabs/alphamap#31]
Hi, 

I am not sure if I completely understood how to use Alphamap correctly: Being an Arabidopsis guy, I mainly work with the databases from Araport or TAIR with some individual changes and additions but not Uniprot. Does my evidence.txt need to contain the respective Uniprot identifiers for Alphamap to work at all? Or could I also use databases I edited? I am mainly interested to compare sequence coverage between isoforms etc.. 

At the moment I get the following errors when I try to upload my evidence.txt from my MaxQuant Run (2.0.3.0): 

"The columns necessary for further analysis cannot be extracted from the first experimental file. Please check the data uploading instructions for a particular software tool."

The console says: 

param\parameterized.py:337: DtypeWarning:

Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.

So is it me using the tool incorrectly or is there a fix to my problem? 

Many thanks,
Nils

**Comment by ibludau** [comment]
Hi Nils, 
I'm sorry for the late reply. I actually used your data and it worked perfectly fine for me. 
I also get a warning message, but that should not have any impact on the results. 
I do not get the error: "The columns necessary for further analysis cannot be extracted from the first experimental file. Please check the data uploading instructions for a particular software tool."

Could it be that you work with an earlier release of alphamap?
I would recommend to uninstall it completely and then reinstall from scratch (Release version 0.1.5). 
Please let me know in case you still encounter problems afterwards.

Best,
Isabell
