### ISSUE TITLE
Uninformative separator error

### ISSUE THREAD

**Issue by JuliaS92** [MannLabs/alphamap#6]
In file: alphamap/importing.py
Error: local variable 'sep' referenced before assignment
Function: import_data(file, sample, verbose, dashboard)

I tried to read a file without any file-extension (easily fixed on my end).
I'd still suggest either a default separator if the filetype doesn't match any defined ones, or an informative message that the filetype isn't supported.

**Comment by EugeniaVoytik** [comment]
I've added an informative error message as a solution.
